### ISSUE TITLE
Title for statistics page

### ISSUE THREAD

**Issue by rad96** [Metron-Project/metron#301]
Can we get title for statistics page?
![изображение](https://github.com/user-attachments/assets/bd04a34a-5306-4143-9d1c-4688d14d1ba7)

**Comment by bpepple** [comment]
This should be an easy fix. The statistic page is a simple request page, unlike the majority of other views which sets the title automatically based on the model.

I'm preparing for an OS upgrade of the server this weekend, so I won't be fix this until next week at the earliest.
