### ISSUE TITLE
Do not reset issue filters after search

### ISSUE THREAD

**Issue by rad96** [Metron-Project/metron#304]
If I searched for issue, it would be nice to not reset filters I set after search, so I can adjust it to be little more precise if I not found something I was looking for, or my search was too broad

**Comment by bpepple** [comment]
I don't think that would be a great behavior to implement, since most of the time you wouldn't want the old query criteria there if you wanted to do a new search.

Using a browsers default behavior of using the go-back one page would produce the results you're looking for.
